<?php

namespace AppBundle\Entity;

use AppBundle\Utils\TwitterProvider;
/**
 * AuthorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AuthorRepository extends \Doctrine\ORM\EntityRepository
{
    public function update($name, $em, $settings)
    {
    	$author = $this->findOneByTwitterId($name);
    	$twp = new TwitterProvider($settings);
    	$tr=$em->getRepository('AppBundle:Tweet');
        $authorTweets = $twp->getTweets($name);
        foreach ($authorTweets as $key => $tweet) {
        	$copy = $tr->findOneByTwitterId($tweet->id_str);
        	if(!$copy){
            	$myTweet = new Tweet($tweet);
	            if($myTweet->getDisplayUrl()){
	                $author->addTweet($myTweet);
	                $em->persist($myTweet);
	            }
	        }
        }
        $author->setUpdateDate(new \DateTime());
        $em->flush();
        $em->clear();
    }
}
