<?php

namespace AppBundle\Entity;

/**
 * TweetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TweetRepository extends \Doctrine\ORM\EntityRepository
{
	public function findLastTweets($border, $order, $typeId)
	{
	    $qb = $this->createQueryBuilder('a');

	    $qb->join('a.author', 'auth');
	    $qb->where('a.twitterId'.$order.':border');
	    $qb->andWhere('auth.type = :typeId');
	    $qb->orderBy('a.creationDate', 'DESC');
	    $qb->setMaxResults(4);
	    $qb->setParameter('border', $border);
	    $qb->setParameter('typeId', $typeId);
	    return $qb->getQuery()->getResult();
	}
	public function findByAuthorType($typeId)
	{
	    $qb = $this->createQueryBuilder('a');
	    $qb->join('a.author', 'auth');
	    $qb->where('auth.type = :typeId');
	    $qb->orderBy('a.creationDate', 'DESC');
	    $qb->setMaxResults(4);
	    $qb->setParameter('typeId', $typeId);
	    return $qb->getQuery()->getResult();
	}
}
